#TestData=[(Test Data 01),(Test Data 02)....]
#(Test Data 0n) = ([hand1],[hand2],'expected result')
#handn=[('suit','val'),('suit','val')...]
from testdata_hands import *
import pytest
TestData =[pytest.param(hand_royal_flush_1,hand_royal_flush_2,'Tie',id='TC03_01_royal_flush'),#Both player has royal flush hand of 5
            pytest.param(hand_royal_flush_3,hand_royal_flush_4,'Tie',id='TC03_02_royal_flush'),#Both player has royal flush hand of 3
            pytest.param(hand_royal_flush_5,hand_royal_flush_6,'Tie',id='TC03_03_royal_flush'),#Both player has royal flush hand of 2
            pytest.param(hand_royal_flush_1,hand_straight_flush_1,'Player1',id='TC03_04_royal_flush'),#Player 1 royal flush player 2 straight flush hand of 5
            pytest.param(hand_straight_flush_2,hand_royal_flush_2,'Player2',id='TC03_05_royal_flush'),#Player 2 royal flush player 1 straight flush hand of 5
            pytest.param(hand_royal_flush_3,hand_straight_flush_3,'Player1',id='TC03_06_royal_flush'),#Player 1 royal flush player 2 straight flush hand of 3
            pytest.param(hand_straight_flush_4,hand_royal_flush_4,'Player2',id='TC03_07_royal_flush'),#Player 2 royal flush player 1 straight flush hand of 3
            pytest.param(hand_royal_flush_5,hand_straight_flush_5,'Player1',id='TC03_08_royal_flush'),#Player 1 royal flush player 2 straight flush hand of 2
            pytest.param(hand_straight_flush_6,hand_royal_flush_6,'Player2',id='TC03_09_royal_flush'),#Player 2 royal flush player 1 straight flush hand of 2
            pytest.param(hand_straight_flush_1,hand_straight_flush_2,'Tie',id='TC03_10_straight_flush'),#Both player straight flush hand of 5
            pytest.param(hand_straight_flush_3,hand_straight_flush_4,'Tie',id='TC03_11_straight_flush'),#Both player straight flush hand of 3
            pytest.param(hand_straight_flush_5,hand_straight_flush_6,'Tie',id='TC03_12_straight_flush'),#Both player straight flush hand of 2
            pytest.param(hand_straight_flush_1,hand_four_of_a_kind_1,'Player1',id='TC03_13_straight_flush'),#Player 1 staright flush Player 2 Four of a kind hand of 5
            pytest.param(hand_four_of_a_kind_2,hand_straight_flush_2,'Player2',id='TC03_14_straight_flush'),#Player 2 staright flush Player 1 Four of a kind hand of 5
            pytest.param(hand_straight_flush_3,hand_flush_3,'Player1',id='TC03_15_straight_flush'),#Player 1 staright flush Player 2 flush hand of 3
            pytest.param(hand_flush_4,hand_straight_flush_4,'Player2',id='TC03_16_straight_flush'),#Player 2 staright flush Player 1 flush hand of 3
            pytest.param(hand_straight_flush_5,hand_flush_5,'Player1',id='TC03_17_straight_flush'),#Player 1 staright flush Player 2 flush hand of 2
            pytest.param(hand_flush_6,hand_straight_flush_6,'Player2',id='TC03_18_straight_flush'),#Player 2 staright flush Player 1 flush hand of 2
            pytest.param(hand_four_of_a_kind_1,hand_four_of_a_kind_2,'Tie',id='TC03_19_four_of_a_kind'),#Both player has four of a kind
            pytest.param(hand_four_of_a_kind_1,hand_full_house_1,'Player1',id='TC03_20_four_of_a_kind'),#Player 1 four of a kind Player 2 full house
            pytest.param(hand_full_house_2,hand_four_of_a_kind_2,'Player2',id='TC03_21_four_of_a_kind'),#Player 2 four of a kind Player 1 full house            
            pytest.param(hand_full_house_1,hand_full_house_2,'Tie',id='TC03_22_full_house'),#Both player has full house
            pytest.param(hand_full_house_1,hand_flush_1,'Player1',id='TC03_23_full_house'),#Player 1 full house Player 2 flush
            pytest.param(hand_flush_2,hand_full_house_2,'Player2',id='TC03_24_full_house'),#Player 2 full house Player 1 flush
            pytest.param(hand_flush_1,hand_flush_2,'Tie',id='TC03_25_flush'),#Both player has flush hand of 5
            pytest.param(hand_flush_3,hand_flush_4,'Tie',id='TC03_26_flush'),#Both player has flush hand of 3
            pytest.param(hand_flush_5,hand_flush_6,'Tie',id='TC03_27_flush'),#Both player has flush hand of 2                        
            pytest.param(hand_flush_1,hand_straight_1,'Player1',id='TC03_28_flush'),#Player 1 flush Player 2 straight hand of 5
            pytest.param(hand_straight_2,hand_flush_2,'Player2',id='TC03_29_flush'),#Player 2 flush Player 1 straight hand of 5
            pytest.param(hand_flush_3,hand_straight_3,'Player1',id='TC03_30_flush'),#Player 1 flush Player 2 straight hand of 3
            pytest.param(hand_straight_4,hand_flush_4,'Player2',id='TC03_31_flush'),#Player 2 flush Player 1 straight hand of 3
            pytest.param(hand_flush_5,hand_straight_5,'Player1',id='TC03_32_flush'),#Player 1 flush Player 2 straight hand of 2
            pytest.param(hand_straight_6,hand_flush_6,'Player2',id='TC03_33_flush'),#Player 2 flush Player 1 straight hand of 2
            pytest.param(hand_straight_1,hand_straight_2,'Tie',id='TC03_34_straight'),#Both player has straight hand of 5
            pytest.param(hand_straight_3,hand_straight_4,'Tie',id='TC03_35_straight'),#Both player has straight hand of 3
            pytest.param(hand_straight_5,hand_straight_6,'Tie',id='TC03_36_straight'),#Both player has straight hand of 2                        
            pytest.param(hand_straight_1,hand_three_of_a_kind_1,'Player1',id='TC03_37_straight'),#Player 1 straight Player 2 three of a kind hand of 5
            pytest.param(hand_three_of_a_kind_2,hand_straight_2,'Player2',id='TC03_38_straight'),#Player 2 straight Player 1 three of a kind hand of 5
            pytest.param(hand_straight_3,hand_three_of_a_kind_4,'Player1',id='TC03_39_straight'),#Player 1 straight Player 2 three of a kind hand of 3
            pytest.param(hand_three_of_a_kind_5,hand_straight_4,'Player2',id='TC03_40_straight'),#Player 2 straight Player 1 three of a kind hand of 3
            pytest.param(hand_straight_5,hand_one_pair_6,'Player1',id='TC03_41_straight'),#Player 1 straight Player 2 one pair hand of 2
            pytest.param(hand_one_pair_7,hand_straight_6,'Player2',id='TC03_42_straight'),#Player 2 straight Player 1 one pair hand of 2
            pytest.param(hand_three_of_a_kind_1,hand_three_of_a_kind_2,'Tie',id='TC03_43_three_of_kind'),#Both player has three of a kind hand of 5
            pytest.param(hand_three_of_a_kind_4,hand_three_of_a_kind_5,'Tie',id='TC03_44_three_of_kind'),#Both player has three of a kind hand of 3
            pytest.param(hand_three_of_a_kind_1,hand_two_pair_1,'Player1',id='TC03_45_three_of_kind'),#Player 1 three of a kind Player 2 two pair hand of 5
            pytest.param(hand_two_pair_2,hand_three_of_a_kind_2,'Player2',id='TC03_46_three_of_kind'),#Player 2 three of a kind Player 1 two pair hand of 5
            pytest.param(hand_three_of_a_kind_3,hand_one_pair_3,'Player1',id='TC03_47_three_of_kind'),#Player 1 three of a kind Player 2 one pair hand of 3
            pytest.param(hand_one_pair_4,hand_three_of_a_kind_4,'Player2',id='TC03_48_three_of_kind'),#Player 2 three of a kind Player 1 one pair of a kind hand of 3
            pytest.param(hand_two_pair_1,hand_two_pair_2,'Tie',id='TC03_49_two_pair'),#Both player has two pair 
            pytest.param(hand_two_pair_1,hand_one_pair_1,'Player1',id='TC03_50_two_pair'),#Player 1 two pair Player 2 one pair
            pytest.param(hand_one_pair_2,hand_two_pair_2,'Player2',id='TC03_51_two_pair'),#Player 2 two pair Player 1 one pair
            pytest.param(hand_one_pair_1,hand_one_pair_2,'Tie',id='TC03_52_one_pair'),#Both player has one pair hand of 5
            pytest.param(hand_one_pair_4,hand_one_pair_5,'Tie',id='TC03_53_one_pair'),#Both player has one pair hand of 3
            pytest.param(hand_one_pair_6,hand_one_pair_7,'Tie',id='TC03_54_one_pair'),#Both player has one pair hand of 2
            pytest.param(hand_one_pair_1,hand_None_1,'Player1',id='TC03_55_high_card'),#Player 1 one pair 2 high card hand of 5
            pytest.param(hand_None_2,hand_one_pair_2,'Player2',id='TC03_56_high_card'),#Player 2 one pair 1 high card hand of 5
            pytest.param(hand_one_pair_4,hand_None_3,'Player1',id='TC03_57_high_card'),#Player 1 one pair 2 high card hand of 3
            pytest.param(hand_None_4,hand_one_pair_5,'Player2',id='TC03_58_high_card'),#Player 2 one pair 1 high card hand of 3
            pytest.param(hand_one_pair_6,hand_None_5,'Player1',id='TC03_59_high_card'),#Player 1 one pair 2 high card hand of 2
            pytest.param(hand_None_6,hand_one_pair_7,'Player2',id='TC03_60_high_card'),#Player 2 one pair 1 high card hand of 2
            ]
